name: Run stocks

on:
  schedule:
    - cron: '0 1 * * *'  # Ежедневно в 04:00 по МСК (UTC+3)
  workflow_dispatch:

jobs:
  stock-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Decode Google Service Account Key
        run: echo "${{ secrets.GOOGLE_SHEETS }}" | base64 --decode > key.json

      - name: Run get_stocks
        run: python -m scripts.get_stocks

      - name: Cleanup key file
        if: always()
        run: rm -f key.json
